WebApp/ViewModels/GridCollectionViewModel.cs
using WebApp.Models.dto;

namespace WebApp.ViewModels;

public class GridCollectionViewModel
{
    public string? Title { get; set; }
    public IEnumerable<string>? Categories { get; set; }
    public IEnumerable<Product>? Products { get; set; }

    public bool LoadMore { get; set; } = true;
}

WebApp/ViewModels/ProductDetailsViewModel.cs
using WebApp.Models.dto;
using WebApp.Models.dtos;

namespace WebApp.ViewModels
{
    public class ProductDetailsViewModel
    {
        public Product Product { get; set; } = null!;
        public IEnumerable<Product> RandomProducts { get; set; } = null!;
        public IEnumerable<Tag> ExistingTags { get; set; } = new List<Tag>();
    }
}

WebApp/ViewModels/ShowcaseViewModel.cs
namespace WebApp.ViewModels
{
    public class ShowcaseViewModel
    {
        public string Ingress { get; set; } = "WELCOME TO BMERKETO SHOP";
        public string Title { get; set; } = "Exclusive Chair gold Collection";
    }
}

WebApp/ViewModels/UpToSellViewModel.cs
namespace WebApp.ViewModels
{
    public class UpToSellViewModel
    {
        public string Title { get; set; } = "UP TO SELL";

        public string BigTitle { get; set; } = "50% OFF";
        public string Ingress { get; set; } = "Get the Best Price";
        public string Text { get; set; } = "Get the best daily offer et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren no sea taki";
    }
}

WebApp/Controllers/AccountController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers
{
    [Authorize] 
    //Skydda sidan i utloggat läge
    public class AccountController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WebApp/Controllers/ContactsController.cs
using Microsoft.AspNetCore.Mvc;
using WebApp.Helpers.Services;
using WebApp.ViewModels;

namespace WebApp.Controllers;

public class ContactsController : Controller
{
    private readonly ContactFormService _contactFormService;

    public ContactsController(ContactFormService contactFormService)
    {
        _contactFormService = contactFormService;
    }

    public IActionResult Index()
    {
        return View();
    }

    [HttpPost]
    public async Task <IActionResult> Index (ContactformViewModel contactsViewModel)
    {
        if (ModelState.IsValid)
        {
            if (await _contactFormService.CreateAsync(contactsViewModel))
                return RedirectToAction("index", "home");

            ModelState.AddModelError("", "Något gick fel");
        }
        return View();
    }


}

WebApp/Controllers/DeniedController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers
{
    public class DeniedController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WebApp/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using WebApp.Helpers.Services;
using WebApp.Models.dto;
using WebApp.ViewModels;

namespace WebApp.Controllers;

public class ProductsController : Controller
{
    private readonly ProductService _productService;

    public ProductsController(ProductService productService)
    {
        _productService = productService;
    }

    public async Task<IActionResult> Index()
    {
        var viewModel = new GridCollectionViewModel
        {
            Products = await _productService.GetAllAsync(), 
        };

        return View(viewModel);
    }

    [HttpGet("/products/details/{articleNumber}")]
    public async Task<IActionResult> Details(string articlenumber)
    {
        var product = await _productService.GetAsync(articlenumber);

        if (product == null)
        {
            return NotFound(); // Hantera om produkten inte hittas
        }

        var viewModel = new ProductDetailsViewModel
        {

            RandomProducts = await _productService.GetRandomProductsAsync(4) // Hämta slumpmässiga produkter.
        };

        var productModel = new Product
        {
            ArticleNumber = product.ArticleNumber,
            Description = product.Description,
            Name = product.Name,
            Price = product.Price,
            ImageUrl= product.ImageUrl
        };

        var detailsViewModel = new ProductDetailsViewModel
        {
            Product = productModel,
            RandomProducts = await _productService.GetRandomProductsAsync(4), // Hämta slumpmässiga produkter.
            ExistingTags = product.Tags
        };

        return View(detailsViewModel);
    }

    private IEnumerable<Product> GetRandomProducts(IEnumerable<Product> products, int count)
    {
        var random = new Random();
        var randomProducts = products.OrderBy(p => random.Next()).Take(count);
        return randomProducts;
    }

    public IActionResult Search()
    {
        return View();
    }

    public IActionResult Cart()
    {
        return View();
    }
}

WebApp/Views/Partials/_Breadcrumb.cshtml
<section class="breadcrumb">
    <div class="container">
        <div class="content">
            <h1>CONTACT</h1>
            <ul>
                <li>HOME</li>
                <li>CONTACT</li>
            </ul>
        </div>
    </div>
</section>

WebApp/Views/Partials/_CollectionContentItem.cshtml
@model WebApp.Models.dto.Product

<a asp-controller="products" asp-action="details" asp-route-id="@Model.ArticleNumber" class="collection-content-item">
    <img src="~/images/placeholders/@Model.ImageUrl" alt="@Model.Name">
<div class="body">
    <div class="title">@Model.Name</div>
    <div class="info">
        <div class="price">@Model.Price</div>
        <i class="add-cart fa-regular fa-cart-plus"></i>
    </div>
</div>
 </a>

WebApp/Views/Partials/_Denied.cshtml
<section class="admin-view">
    <div class="container">
        <div class="title">Du har inte behörighet till denna sida</div>
        </div>
</section>

WebApp/Views/Partials/_FooterPartial.cshtml
<footer>
    <div class="container">
        © @DateTime.Now.Year bmerketo. All right reserved.
    </div>
</footer>

WebApp/Views/Partials/_GoogleMapPartial.cshtml
<section class="map">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3323.846379992451!2d18.021943310261673!3d59.34492585222009!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x465f9d9d263b022d%3A0x82fc0f30ed84f9ed!2sNackademin!5e0!3m2!1ssv!2sse!4v1679451477145!5m2!1ssv!2sse" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
</section>

WebApp/Views/Partials/_GridCollection.cshtml
@model GridCollectionViewModel

@{
    ViewData["Title"] = "Produkter";
}

@if (Model != null)
{
    <section class="grid-collection">
        <div class="container">
            @if (!string.IsNullOrEmpty(Model.Title))
            {
                <h1 class="title">@Model.Title</h1>
            }

            @if (Model.Categories != null)
            {
                <ul class="categories">
                    @foreach (var category in Model.Categories)
                    {
                        <li class="category-item">@category</li>
                    }
                </ul>
            }

            @if (Model.Products != null)
            {
                <div class="grid">
                    @foreach (var productViewModel in Model.Products)
                    {
                        <partial name="/Views/Partials/_GridCollectionItem.cshtml" model="productViewModel" />
                    }
                </div>
            }

            @if (Model.LoadMore)
            {
                <div class="load-more">
                    <button class="btn-outline-white">LOAD MORE <i class="fa-solid fa-rotate-right"></i></button>
                </div>
            }
        </div>
    </section>
}

WebApp/Views/Partials/_GridCollectionItem.cshtml
@model WebApp.Models.dto.Product

<a asp-controller="products" asp-action="details" asp-route-id="@Model.ArticleNumber" class="collection-item">
<div class="body">
    <div class="title">@Model.Name</div>
        <img src="〜/images/placeholders/@Model.ImageUrl" alt="@Model.Name">
    <div class="info">
        <div class="price">@Model.Price</div>
        <i class="add-cart fa-regular fa-cart-plus"></i>
    </div>
</div>
 </a>

WebApp/Views/Partials/_HeaderPartial.cshtml
<header>
    <div class="container">
        <div class="logo"><img src="images/logo.svg" alt="bmerketo"></div>
        <nav id="menu" class="menu-links">
            <a class="link" asp-controller="Home" asp-action="Index">HOME</a>
            <a class="link" asp-controller="Products" asp-action="Index">PRODUCTS</a>
            <a class="link" asp-controller="Contacts" asp-action="Index">CONTACT</a>
        </nav>
        <nav class="menu-icons">
            <a class="link" asp-controller="Products" asp-action="Search"><i class="fa-regular fa-search"></i></a>
            <a class="link" asp-controller="Account" asp-action="Login">Login</a>
            <a class="link" asp-controller="Cart" asp-action="Index"><i class="fa-solid fa-cart-shopping"></i></a>
        </nav>
        <div class="toggle">
            <button class="btn-toggle btn-outline-white" data-option="toggle" data-target="#menu">
                <i id="icon" class="fa-regular fa-bars"></i>
            </button>
        </div>
    </div>
</header>

WebApp/Views/Partials/_ProductBreadCrumb.cshtml
<section class="product-breadcrumb">
    <div class="container">
        <div class="content">
            <h1>SHOP</h1>
            <ul>
                <li>HOME</li>
                <li>PRODUCTS</li>
                <li>DETAILS</li>
            </ul>
        </div>
    </div>
</section>

WebApp/Views/Partials/_ProductDetailsBottom.cshtml
    <section class="showcase-bottom">
        <div class="container">
            <div class="image">
            <img src="~/images/placeholders/200x122.svg" alt="">
            <img src="~/images/placeholders/200x122.svg" alt="">
            <img src="~/images/placeholders/200x122.svg" alt="">
            <img src="~/images/placeholders/200x122.svg" alt="">
            </div>
        </div>
    </section>

WebApp/Views/Partials/_ProductDetailsInfo.cshtml
@model ProductDetailsViewModel

<section class="product-info">
        <div class="container">
            <button class="btn-outline-white">DESCRIPTION</button>
            <button class="btn-outline-white">ADDITIONAL INFO</button>
            <button class="btn-outline-white">REVIEWS (0)</button>
            <button class="btn-outline-white">REVIEWS (0)</button>
        <div class="title">Här kan det stå en titel</div>
        <div class="product-info">
            <div class="text">
                Här kan det stå ännu mer utförlig information om produkten.
            </div>
            <div class="image">
                <img src="~/images/placeholders/@Model.Product.ImageUrl" alt="@Model.Product.Name">
            </div>
            </div>
        </div>
    </section>

WebApp/Views/Partials/_ProductDetailsRelated.cshtml
@model ProductDetailsViewModel

<section class="grid-collection">
    <div class="container">
        <div class="title">Related Products</div>
        <div class="grid">
            @foreach (var randomProduct in Model.RandomProducts)
            {
            <partial name="/Views/Partials/_GridCollectionItem.cshtml" model="randomProduct" />
            }

        </div>
    </div>
</section>

WebApp/Views/Partials/_TopSelling.cshtml
@model GridCollectionViewModel

@{
    ViewData["Title"] = "Produkter";
    var products = await productService.GetAllAsync();
}
@if (Model != null)
{
    <section class="top-selling">
        <div class="container-fluid">
            @if (!string.IsNullOrEmpty(Model.Title))
            {
                <h1 class="title">@Model.Title</h1>
            }

            @if (Model.Categories != null)
            {
                <ul class="categories">
                    @foreach (var category in Model.Categories)
                    {
                        <li class="category-item">@category</li>
                    }
                </ul>

            }
            @if (Model.Products != null)
            {
                <div class="collection-grid">
                    @foreach (var item in Model.Products)
                    {
                        <partial name="/Views/Partials/_GridCollectionItem.cshtml" model="item" />
                    }
                </div>
            }

            @if (Model.LoadMore)
            {
                <div class="load-more">
                    <button class="btn-outline-white me-1"><i class="fa-solid fa-chevron-left"></i></button>
                    <button class="btn-outline-white ms-1"><i class="fa-solid fa-chevron-right"></i></button>
                </div>
            }

        </div>
    </section>
}

WebApp/Views/Partials/_UpToSellPartial.cshtml
<section class="up-to-sell">
    <div class="container">
        <div class="collection-grid">
            <div class="item-1">
                <!-- collection-item start -->
                <a href="#" class="collection-item">
                    <img src="images/placeholders/369x310.svg" alt="">
                    <div class="body">
                        <div class="title">Apple watch collection</div>
                        <div class="info">
                            <div class="price">$30.00</div>
                            <i class="add-cart fa-regular fa-cart-plus"></i>
                        </div>
                    </div>
                </a>
                <!-- collection-item end -->
            </div>
            <div class="discover">
                <!-- collection-content start -->
                <div class="collection-content">
                    <div class="container">
                        <div class="title-red">UP TO SELL</div>
                        <div class="title">50% OFF</div>
                        <div class="ingress">Get the Best Price</div>
                        <div class="text">Get the best daily offer et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren no sea taki</div>
                        <a href="#" class="link">Discover More</a>
                    </div>
                </div>
                <!-- collection-content end -->
            </div>
            <div class="item-2">
                <!-- collection-item start -->
                <a href="#" class="collection-item">
                    <img src="images/placeholders/369x310.svg" alt="">
                    <div class="body">
                        <div class="title">Apple watch collection</div>
                        <div class="info">
                            <div class="price">$30.00</div>
                            <i class="add-cart fa-regular fa-cart-plus"></i>
                        </div>
                    </div>
                </a>
                <!-- collection-item end -->
            </div>
        </div>
    </div>
</section>